name: Databricks CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Databricks CLI
      run: pip install databricks-cli

    - name: Deploy Notebooks
      run: |
        databricks workspace import_dir ./notebooks /Users/eleanorahsa@gmail.com/notebooks -o
